[package]
name = "faizdzn/ro-pinia"
description = "A state management like Pinia on Roblox"
version = "0.1.1"
license = "MIT"
realm = "shared"
repository = "https://github.com/Faizdzn/ro-pinia"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]

[dev-dependencies]
Jest = "roblox/jest@=3.20.0"
JestGlobals = "roblox/jest-globals@=3.20.0"